# Generated by Django 4.0.1 on 2022-01-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
